# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm "virtualbox" do |vb|
    vb.customize['modifyvm', :id, '--name', 'app']
    vb.customize['modifyvm', :id, '--memory', '512']
  end

  config.vm.box = "precise64_with_ruby193"
  config.vm.hostname = "app"
  config.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2222, auto_correct: true
  config.vm.network :forwarded_port, guest: 80, host: 4567
  config.vm.network :private_network, ip: "33.33.13.37"
  config.vm.synced_folder "../massiveapp_ops", "/etc/puppet"
end
