# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :app do |app_config|

    app_config.vm "virtualbox" do |vb|
      vb.customize['modifyvm', :id, '--name', 'app']
      vb.customize['modifyvm', :id, '--memory', '512']
    end

    app_config.vm.box = "precise64_with_ruby193"
    app_config.vm.hostname = "app"
    app_config.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2222, auto_correct: true
    app_config.vm.network :forwarded_port, guest: 80, host: 4567
    app_config.vm.network :private_network, ip: "33.33.13.37"
  end

  config.vm.define :db do |db_config|
    db_config.vm "virtualbox" do |vb|
      vb.customize["modifyvm", :id, "--name", "db"]
      vb.customize["modifyvm", :id, "--memory", "512"]
    end

    db_config.vm.box = "precise64_with_ruby193"
    db_config.vm.hostname = "db"
    db_config.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2222, auto_correct: true
    db_config.vm.network :private_network, ip: "33.33.13.38"
  end

end
